image: adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine-slim

variables:
  DOCKER_DRIVER: overlay
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - build
  - test
  - visualize
  - package

include:
  - local: /commons/.gitlab-ci.yml
  - local: /adapters/.gitlab-ci.yml
  - local: /algorithm/.gitlab-ci.yml
  - local: /despachalo-app/.gitlab-ci.yml
  - local: /despachalo-core/.gitlab-ci.yml

gradle-build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    expire_in: 1h
    paths:
      - ./**/build/libs/*.jar
  only:
    - master
    - production
    - merge_requests


sonarcloud-check:
  stage: visualize
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ./gradlew codeCoverageReport
    - ./gradlew sonarqube
  only:
    - master
    - production
    - merge_requests


coverage-gitlab:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml src/main/java > build/cobertura.xml
    - python /opt/source2filename.py build/cobertura.xml
  allow_failure: true
  artifacts:
    reports:
      cobertura: build/cobertura.xml
  only:
    - merge_requests

docker-registry:
  image: docker:latest
  stage: package
  variables:
    APP_VERSION: 1.0.0
  services:
    - docker:dind
  before_script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - APP_IMAGE_NAME=${CI_REGISTRY_IMAGE}:${APP_VERSION}-${COMMIT_TIME}-${CI_COMMIT_SHORT_SHA}
    - APP_IMAGE_LATEST=${CI_REGISTRY_IMAGE}:latest
  script:
    - docker build -t $APP_IMAGE_NAME .
    - docker tag $APP_IMAGE_NAME $APP_IMAGE_LATEST
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push $APP_IMAGE_NAME
    - docker push $APP_IMAGE_LATEST
  only:
    - master
    - production
