image: adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine-slim

variables:
  DOCKER_DRIVER: overlay
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - build
  - test
  - visualize


gradle-build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    expire_in: 1h
    paths:
      - ./**/build/libs/*.jar
  only:
    - master
    - production
    - merge_requests


test-all:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/reports/jacoco/test/jacocoTestReport.xml
    reports:
      junit:
        - ./**/build/test-results/test/TEST-*.xml
  only:
    - master
    - production
    - merge_requests


sonarcloud-check:
  stage: visualize
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ./gradlew sonarqube
  only:
    - master
    - production
    - merge_requests


coverage-gitlab:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml src/main/java > build/cobertura.xml
    - python /opt/source2filename.py build/cobertura.xml
  needs:
    - unit-test
  dependencies:
    - unit-test
  artifacts:
    reports:
      cobertura: build/cobertura.xml
  only:
    - merge_requests
