
persistence-integration-test:
  stage: test
  script:
    - ./gradlew :adapters:despachalo-persistence:test
  artifacts:
    paths:
      - adapters/despachalo-persistence/build/jacoco/test.exec
    reports:
      junit:
        - adapters/despachalo-persistence/build/test-results/test/TEST-*.xml
  allow_failure: true
  only:
    - master
    - production
    - merge_requests
