server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/despachalo
    username: despachalo
    password: despachalo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  data:
    web:
      pageable:
        size-parameter: pagesize
        page-parameter: page
        default-page-size: 10
        max-page-size: 50

logging:
  file:
    path: logs/
  level:
    org.hibernate.SQL: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
