INSERT INTO rol(id, nombre) VALUES (2, 'ANALISTA');

INSERT INTO centro_distribucion(direccion, eliminado, ubi_latitud, ubi_longitud, nombre)
VALUES ('Av. Grau', false, 0.01, 0.01, 'Ica Central');

-- user: analistaXX@despachalo.pe
-- pass: analista
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345601', 'DNI', 'analista01@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '01', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345602', 'DNI', 'analista02@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '02', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345603', 'DNI', 'analista03@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '03', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345604', 'DNI', 'analista04@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '01', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345605', 'DNI', 'analista05@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '05', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345606', 'DNI', 'analista06@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '06', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345607', 'DNI', 'analista07@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '07', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345608', 'DNI', 'analista08@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '08', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345609', 'DNI', 'analista09@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '09', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345610', 'DNI', 'analista10@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '10', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345611', 'DNI', 'analista11@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '11', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345612', 'DNI', 'analista12@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '12', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345613', 'DNI', 'analista13@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '13', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345614', 'DNI', 'analista14@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '14', 'Analista', 2);
INSERT INTO usuario(centro_id, activo, num_documento, tipo_documento, correo, contrasena_hash, es_admin, apellidos, nombres, rol_id) VALUES (1, true, '12345615', 'DNI', 'analista15@despachalo.pe', '$2a$12$OFuPQqCCRGkshVO7iKgciek3HWwoKIs4dW5q.8f/Y/tazxgVFRRS6', false, '15', 'Analista', 2);
