
algorithm-white-box-test:
  stage: test
  script:
    - ./gradlew :algorithm:test
  artifacts:
    paths:
      - algorithm/build/jacoco/test.exec
    reports:
      junit:
        - algorithm/build/test-results/test/TEST-*.xml
  only:
    - master
    - production
    - merge_requests
