
core-unit-test:
  stage: test
  script:
    - ./gradlew :despachalo-core:test
  artifacts:
    reports:
      junit:
        - despachalo-core/build/test-results/test/TEST-*.xml
  only:
    - master
    - production
    - merge_requests
